const express = require('express');
const cors = require('cors');
const path = require('path');
const { GoogleSpreadsheet } = require('google-spreadsheet');

const app = express();
const PORT = process.env.PORT || 3000;

// Google Sheets setup
const SHEET_ID = process.env.GOOGLE_SHEET_ID;
let CREDS = null;
try {
  CREDS = process.env.GOOGLE_CREDS_JSON ? JSON.parse(process.env.GOOGLE_CREDS_JSON) : null;
  console.log('Service Account Email:', CREDS?.client_email);
  
  if (!CREDS?.private_key || !CREDS?.client_email) {
    throw new Error('Missing required credential fields');
  }
} catch (e) {
  console.error('Invalid GOOGLE_CREDS_JSON:', e.message);
  console.error('Please ensure your service account credentials are properly formatted and contain all required fields');
}

// Sheet references
let doc = null;
let stationsSheet = null;
let bookingsSheet = null;

// Initialize Google Sheets
async function initGoogleSheets() {
  if (!SHEET_ID) {
    throw new Error('GOOGLE_SHEET_ID environment variable is missing');
  }
  if (!CREDS) {
    throw new Error('Invalid or missing GOOGLE_CREDS_JSON environment variable');
  }

  try {
    console.log('Initializing Google Sheets with Sheet ID:', SHEET_ID);
    doc = new GoogleSpreadsheet(SHEET_ID);
    
    // Initialize auth - see more available options at https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    console.log('Attempting to authenticate with service account:', CREDS.client_email);
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: CREDS.client_email,
      private_key: CREDS.private_key.replace(/\\n/g, '\n'),
      scopes: [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive.file',
      ],
    });

    await doc.loadInfo();
    console.log('Spreadsheet loaded:', doc.title);
    
    // Get or create sheets
    stationsSheet = doc.sheetsByTitle['Stations'];
    if (!stationsSheet) {
      console.log('Creating Stations sheet...');
      stationsSheet = await doc.addSheet({ 
        title: 'Stations', 
        headerValues: ['id', 'station_name', 'specs', 'status', 'created_at'] 
      });
      console.log('Stations sheet created successfully');
    } else {
      console.log('Found existing Stations sheet');
    }
    
    bookingsSheet = doc.sheetsByTitle['Bookings'];
    if (!bookingsSheet) {
      console.log('Creating Bookings sheet...');
      bookingsSheet = await doc.addSheet({ 
        title: 'Bookings', 
        headerValues: [
          'id', 'user_name', 'contact', 'station_id', 'booking_date', 
          'start_time', 'end_time', 'duration_hours', 'total_price', 
          'status', 'booking_code', 'created_at'
        ] 
      });
      console.log('Bookings sheet created successfully');
    } else {
      console.log('Found existing Bookings sheet');
    }

    // Initialize stations if empty
    console.log('Loading stations data...');
    await stationsSheet.loadCells();
    const stations = await stationsSheet.getRows();
    
    if (!stations || stations.length === 0) {
      console.log('No stations found. Initializing default stations...');
      
      // Initialize PC stations (1-5)
      for (let i = 1; i <= 5; i++) {
        console.log(`Creating PC Station ${i}...`);
        await stationsSheet.addRow({
          id: i,
          station_name: `Station ${i}`,
          specs: 'PC',
          status: 'available',
          created_at: new Date().toISOString()
        });
      }
      
      // Initialize PS5 stations (6-8)
      for (let i = 6; i <= 8; i++) {
        console.log(`Creating PS5 Station ${i}...`);
        await stationsSheet.addRow({
          id: i,
          station_name: `Station ${i}`,
          specs: 'PS5',
          status: 'available',
          created_at: new Date().toISOString()
        });
      }
      
      console.log('All stations initialized successfully');
    } else {
      console.log(`Found ${stations.length} existing stations`);
    }

    console.log('✅ Google Sheets initialized');
    return true;
  } catch (err) {
    console.error('❌ Google Sheets init error:', err);
    console.error('Additional error details:', {
      message: err.message,
      code: err.code,
      response: err.response?.data,
    });
    
    if (err.message.includes('getRows')) {
      console.error('\nPossible solutions:');
      console.error('1. Make sure the sheets are properly initialized');
      console.error('2. Try clearing the document cache and reinitializing');
      console.error('3. Verify the sheet structure is correct');
      console.error('4. Check if the service account has sufficient permissions');
    } else if (err.message.includes('permission')) {
      console.error('\nPossible solutions:');
      console.error('1. Verify the service account email address is correct');
      console.error('2. Make sure you have shared the Google Sheet with the service account email');
      console.error('3. Ensure the service account has Editor access to the sheet');
      console.error(`4. Double check that the Sheet ID "${SHEET_ID}" is correct`);
    }
    
    throw err;
  }
}

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'client', 'build')));

// GET stations
app.get('/api/stations', async (req, res) => {
  try {
    const { datetime } = req.query;
    const stations = await stationsSheet.getRows();
    const bookings = await bookingsSheet.getRows();
    
    if (!datetime) {
      // Get current time
      const now = new Date();
      const currentTime = now.toTimeString().substring(0, 5);
      const currentDate = now.toISOString().split('T')[0];

      // Check current bookings
      const currentlyBooked = new Set(
        bookings
          .filter(b => 
            b.booking_date === currentDate && 
            b.status === 'confirmed' &&
            b.start_time <= currentTime &&
            b.end_time > currentTime
          )
          .map(b => b.station_id)
      );

      return res.json(stations.map(s => ({
        id: parseInt(s.id),
        station_name: `${s.station_name} #${s.specs}`,
        specs: s.specs,
        status: currentlyBooked.has(s.id) ? 'Occupied' : 'Available',
        value: s.id
      })));
    }

    // For specific datetime query
    const queryTime = new Date(datetime).toTimeString().substring(0, 5);
    const queryDate = datetime.split('T')[0];

    // Check bookings for the specific time
    const booked = new Set(
      bookings
        .filter(b => 
          b.booking_date === queryDate && 
          b.status === 'confirmed' &&
          b.start_time <= queryTime &&
          b.end_time > queryTime
        )
        .map(b => b.station_id)
    );

    const out = stations.map(s => ({
      id: parseInt(s.id),
      station_name: s.station_name,
      specs: s.specs,
      status: booked.has(s.id) ? 'Occupied' : 'Available'
    }));

    res.json(out);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to load stations' });
  }
});

// GET bookings
app.get('/api/bookings', async (req, res) => {
  try {
    const bookings = await bookingsSheet.getRows();
    const stations = await stationsSheet.getRows();
    
    const rows = bookings.map(b => {
      const station = stations.find(s => s.id === b.station_id);
      return {
        id: parseInt(b.id),
        user_name: b.user_name,
        contact: b.contact,
        station_id: parseInt(b.station_id),
        station_name: station ? station.station_name : null,
        booking_date: b.booking_date,
        start_time: b.start_time,
        end_time: b.end_time,
        duration_hours: parseFloat(b.duration_hours),
        total_price: parseFloat(b.total_price),
        status: b.status,
        booking_code: b.booking_code,
        created_at: b.created_at
      };
    });

    res.json(rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to fetch bookings' });
  }
});

// POST create booking
app.post('/api/bookings', async (req, res) => {
  try {
    const { user_name, contact, station_id, booking_date, start_time, end_time, duration_hours, total_price } = req.body;
    
    if (!user_name || !station_id || !booking_date || !start_time || !end_time) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Check availability
    const bookings = await bookingsSheet.getRows();
    const existingBookings = bookings.filter(
      b => b.station_id === station_id.toString() &&
           b.booking_date === booking_date &&
           b.status === 'confirmed'
    );

    // Check for time overlap
    const hasOverlap = existingBookings.some(booking => {
      const newStartTime = start_time;
      const newEndTime = end_time;
      const existingStartTime = booking.start_time;
      const existingEndTime = booking.end_time;

      return (
        (newStartTime >= existingStartTime && newStartTime < existingEndTime) ||
        (newEndTime > existingStartTime && newEndTime <= existingEndTime) ||
        (newStartTime <= existingStartTime && newEndTime >= existingEndTime)
      );
    });

    if (hasOverlap) {
      return res.status(400).json({ error: 'Station already booked during this time period' });
    }

    // Get next ID
    const nextId = bookings.length > 0 
      ? Math.max(...bookings.map(b => parseInt(b.id))) + 1 
      : 1;

    // Create booking
    const newBooking = {
      id: nextId,
      user_name,
      contact: contact || '',
      station_id: station_id.toString(),
      booking_date,
      start_time,
      end_time,
      duration_hours: duration_hours?.toString() || '',
      total_price: total_price?.toString() || '',
      status: 'confirmed',
      booking_code: `BK${nextId}`,
      created_at: new Date().toISOString()
    };

    await bookingsSheet.addRow(newBooking);
    res.json({ message: 'Booking confirmed', booking: newBooking });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to create booking' });
  }
});

// POST mark booking complete
app.post('/api/bookings/:id/complete', async (req, res) => {
  try {
    const id = req.params.id;
    const bookings = await bookingsSheet.getRows();
    const booking = bookings.find(b => b.id === id);

    if (!booking) {
      return res.status(404).json({ error: 'Booking not found' });
    }

    booking.status = 'completed';
    await booking.save();

    res.json({ message: 'Booking completed', booking: {
      id: parseInt(booking.id),
      user_name: booking.user_name,
      status: booking.status
    }});
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to update booking' });
  }
});

// Serve React app
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'client', 'build', 'index.html'));
});

// Start server
(async () => {
  try {
    console.log('Starting application...');
    console.log('Environment check:');
    console.log('- GOOGLE_SHEET_ID:', process.env.GOOGLE_SHEET_ID ? 'Set' : 'Missing');
    console.log('- GOOGLE_CREDS_JSON:', process.env.GOOGLE_CREDS_JSON ? 'Set' : 'Missing');

    // Initialize Google Sheets - this is critical
    await initGoogleSheets();
    
    // Start the server
    app.listen(PORT, () => {
      console.log(`🚀 Server running on port ${PORT}`);
      console.log('📑 Google Sheets: Connected');
    });
  } catch (err) {
    console.error('Failed to start server:', err);
    console.error('Error details:', {
      name: err.name,
      message: err.message,
      stack: err.stack
    });
    process.exit(1);
  }
})();
